language: python
python:
- '3.4'
#- 'pypy3'
before_install:
- if [ -z "$TRAVIS_TAG" ]; then export DISPLAY=:99.0; fi
- if [ -z "$TRAVIS_TAG" ]; then sh -e /etc/init.d/xvfb start; fi
install:
# - if [ -z "$TRAVIS_TAG" ]; then sudo apt-get update -qq; fi
# - if [ -z "$TRAVIS_TAG" ]; then sudo apt-get build-dep python-pygame; fi
- if [ -z "$TRAVIS_TAG" ]; then pip install .; fi
- if [ -z "$TRAVIS_TAG" ]; then pip install -r requirements.txt; fi
notifications:
  irc: chat.freenode.net#pygame2
  email:
    recipients:
    - leif.theden@gmail.com
    - alecks.g@gmail.com
    on_success: always
    on_failure: always
script: if [ -z "$TRAVIS_TAG" ]; then nosetests; fi
# Need to migrate these settings to use new versions in the pygame2 repo
#after_success:
#- git remote rm origin
#- git remote add origin https://wkmanire:${GITHUBTOKEN}@github.com/wkmanire/pygame.git
#- build/release.sh $((TRAVIS_BUILD_NUMBER))
#env:
#  global:
#    secure: jrblAdTsoRwoBqjVqTXaS27fyJiUq5RdPFTnM/FCl85u/PVQrQ93wRsgliBCdTWTXa1KfOojz+6OIpLi5IzY2ndwQr2myepcpd94qVUustQmExVNVBYwMpCghvAB5Vz95ExaMq+oRbBpgUdNQQa2Hpo4OT+BTqUPWi1o2+LJvjc=
